apiVersion: v1
kind: Pod
metadata:
  name: rucio-client
  namespace: rucio
  # labels:
  #   role: rucio-client
spec:
  containers:
  - name: rucio-client
    image: projectescape/rucio-client:latest
    imagePullPolicy: Always
    env:
    - name: RUCIO_CFG_RUCIO_HOST
      value: "https://vre-rucio.cern.ch"
    - name: RUCIO_CFG_AUTH_HOST
      value: "https://vre-rucio-auth.cern.ch"
    - name: RUCIO_CFG_ACCOUNT
      value: "root"
    - name: RUCIO_CFG_AUTH_TYPE
      value: "userpass"
    - name: RUCIO_CFG_USERNAME
      valueFrom:
        secretKeyRef:
          name: root-account
          key: root-username
    - name: RUCIO_CFG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: root-account
          key: root-password 
    command: ["sleep","3600"]
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
# spec:
#   containers:
#     - name: rucio-client
#       image: projectescape/rucio-client:latest
#       imagePullPolicy: Always
#       volumeMounts:
#         # name must match the volume name below
#         - name: secret-volume
#           mountPath: /etc/secret-volume
#           readOnly: true
#   # The secret data is exposed to Containers in the Pod through a Volume.
#   volumes:
#     - name: secret-volume
#       secret:
#         secretName: test-secret
