# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## replicaCount gives the number of server pods to run
replicaCount: 1

# When set, run extra busybox containers in the relevant pods to also expose the error logs
exposeErrorLogs: True

service:
  type: LoadBalancer
  useSSL: true
  port: 443
  targetPort: https
  portName: https
  annotations:
    loadbalancer.openstack.org/network-id: "d874403a-5d7e-451e-96b4-0648586355b1" 
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
    loadbalancer.openstack.org/cascade-delete: "false"

image:
  repository: rucio/rucio-ui
  tag: release-1.30.0
  pullPolicy: Always

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

proxy:
  rucioProxy: "vre-rucio.cern.ch"
  rucioProxyScheme: "https"
  rucioAuthProxy: "vre-rucio-auth.cern.ch"
  rucioAuthProxyScheme: "https"

## values used to configure apache
httpd_config:
  legacy_dn: "False"
