apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jhub-cvre-iam-secrets
  namespace: jhub
spec:
  encryptedData:
    client_id: AgB40MgVJ6LSkkXsfBSQ9Ple5tiyXVqUu76sc39bEzwUXvhjZzrkdvlW0X8bzMaX66mKwwesla0CNLjO0rjLBdZ8cAgVBX/Kpxo7in/DPfRJIk5BChhHu/RAOo88X8C2GtcQzV6vKXTgRM+ZOadx+cRJMLAoGmg5jSaYmR7NlCy532pEtJ3FWZ81mqqCAF9+S1oOLukGdwF+7ihz/bVEVu0pfOkjAP9oDdl9PBXvl9lhe6Udj5/tiQASaczWUW6YFPCFc+GDZg/q3cEbotoCuWvWOJH1+ygfWeDLps3rc/ah613FZYjf+HmekOfiPOfg1xXzxHrq8dvSnFkLaVe3YNyni5CJVutkooGjxZs9n6Ucw4XufxGFSf3Ho6mGpkrsMmX9XlYoao4A1ItLA6c46YFCv2nLaDpRTAfgzHUP3EuNkM05vB+ssvQL8nyZcaJybrBtCkSNp/pNYyNrPERYNgFXoUyC/+aTGcfzliY75f0F0Hkp+hxuvqkcZhifesE+lxgxLtThLJjGDLpIWcDMMuhiDcbF9vaCwe6cQjQEF8BG6SWZ+2dxXM8T1Yzk2cWs/XqJlpzzuaLEi/DGseEzod+Uvu/eO49smycjlHsYkebMB0KOWpx0opSXhjAm8BLgL7vaPKgbkZfTE19Ks9xZZnCZPeiIvXfuKmwAOTbvbOe8GILasSBJjQ/Y8Yd+78TgSsxDH8eOIQF/JCdZUDemXLzqq1YW1tjgcE31PHBFGGOmRmit67w=
    client_secret: AgBmvm2fe9eJ79Pn1+NEVadUhjAxdVy2TuPVk25Tz9vrK1uuQ/euMCmhoZjzsE5lYWc46AXv/d05aE052RB8ZErIH4jEJzEK2c+b+Lb3guO4Nneh7wkG1hsVYHxiTKZomM71CjE3vud7fR1+YoDEc0kdZCiHI8Ygz+g6Y7yQvzAZSAhc75h0GakJQNrksmzLP92vsi/v4TdploHWSFZ6PWJyJOXTPrEBQgOGFjaywKAowrR+iqm8pE0Q4NTFxHXFY5eptVu4Mv74d8vc6wXATHkreO0c5pw8nVornXh9gOnjXXkpwcDL0PKgxQ9uBg1Ny6jX6OASlmb9o308xbV/kQL1jo7psyz21UX5pCcbVeWlvR6zjGYj8VP3syd0XuvqY4N5tkaqF3US8F9MAQZzLVhLnneoprWbCMCQVP+e3mPO5kLij5Uf1HlhSZfj7ekRjL0MgmhmAiF9iunrzRf90/31nHTo1FDyuXV6ZmYHfvRzjP2cj5jeRvyo2GW+ChFCK5jnW6JdFanUoH9h5UK3LOle04wfH73cBUtt6sA4V52DCPFFmJ8YtYL0DNXcIEp7lR+dJM4/V3VMAeladZrr4ywM40nA5boU3t23gCVlq31ODR6ia8NtCi+DvEtCX/S8H/MN0WN8ch6o7pZFV/BEc9XINrPjvpSDPC/SjNf27zzqIVR/DwrwhPA6uTMkurhrkFPu5+AFcbQ3FuMycJCB9aqWwVzhn1Cg/EQoxM0iHMpMUmeEpk9vu6T7nbEzTVwRIYYiPnKs0CoGO7kkjTVmXpyQVD+Dvpo9PdWnZn1r9YN2mJDl7N4cTY8=
  template:
    metadata:
      creationTimestamp: null
      name: jhub-cvre-iam-secrets
      namespace: jhub

