apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: daemons-vre-rucio-db
  namespace: rucio-vre
spec:
  encryptedData:
    rucio-db: AgClMMIEw5WDtVKnfayyCIM+rDRe2UOyxxf5VbCgfeyts8KHhb9ue51ljphZ3jzU7nZiKktHyGmEpEp1CQnkF+6LqfLWMplhu9wU1luI1vOCsq29UMdXcSYJfk0DYKLXBkHUzeX8Y+Durnc9iVf0u2paSFv3gcvyvOzuPVwEoUXBqplupaqtbI2T/VYFtIwKjD2yiQ6kYtFjdNDz9Xl4XQ7sFrgnuaW6MrlP4+VXCRYMTIdBCwPOoPmgY9GkbwAzXoAw4MsIm9By2uQZFXa4D9EpSX16M4SM+pY6v2YlD3tdumsLcMcCahhZlcVIS3HPMR0+syVIKw24yGWlKG6qyXYtqLXDHKnM0LpzjRUuX6I9Hq2WWY+5gpk05l/Mi1C7Y+niDvx79Q+pki4xBYdogxxEl8PAcClyGXx1zly0+38TRUch7Hep2eYFo4p1khZbIK8pZsTHmGlKcuBQh4L1624ikcLzK54hPHImxCJLa9EDSOObR2XMOGVY5UfRFHiwZA1/mF/WerOVQzTB8bHiolZROaSFF36N8cDhvKMrJEHwpfEYMNaV9Eg2YQ32/mjn6sjMy5+pKgqT5ISHqO+K3nUg7hcgOTddGbWCVjBPHTV0U26N7rTstrP+XE2ikiVgqW/KqNEmwFM0lInO0o4sSqJJYImQrTx1/3qcxvDXZqm8uKvwV4mjDmzzq8vJvgen+qxHAs8v0OVfIwdrw7FhtUSOVSFoU1cFBF4EGERRlKUY0te3uWWuf3c0u0TwBYLPNxmCsRy7O9sDidyLGdL1vbWeiEnixlZmYZsH
  template:
    metadata:
      creationTimestamp: null
      name: daemons-vre-rucio-db
      namespace: rucio-vre

