apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-db
  namespace: rucio
spec:
  encryptedData:
    rucio-db: AgChAAH36Abqup/cVWJg8pdub5bxu5Zzq+l/BVr3Yzeh8fSneGUI6JhKQvzOyVcuSqSUie5KGIvkjjRZpihFCufrm+zDOjVXJZaGaWSog+D8mKKPKAuwrqrCd/XW+Z7JrN3KGCrCI5KR9Q2f3flgeVxM/UTCh+RPc9QAkvhIGg4Y591DQWigYquLaV+pmGd98H8urJTHDkDM5zltkiNDzYXiBIAnluwFpKdhtHfwxWX5A3zjNZVx479glBFhNxosvapXQ6+uxcIqrmkc4UGCbafpVp+I/ZW90GYC3uU9VcDaEZNhtSvKwybmbV22bR0G2DWRRGR8FjJKy4GK5x6XD2LqRLC4raESMK4JDF0uFtX3/h4a1sfevshU0/uT2nTwY3lPEpB0of8KcxXhzrC0Q0c+RGALetmg6FluoKYhFzgUJpjhVn8Xluc9ie4TyAyugteTNiOTINUKREjWbmVFfhn/U9OhWisBtpK36GDd+4nSXjRF3LmMcC0yhD7UpnWy0hVittnc7PHg6mlY+1pMNgT+GGs2WB0yh1QT7xqD8bUKrqzCsk6vErdU4gbP6gASrLXWXcvWB7T1DCerBewx4Vv56qJaZsIm3JmChG0WAGCWXo3vTY1Jm5m+64Qi3GaZCQ+fQ4+5Pu8fJspQ38e/gxDHqd2bV6ftvFCCjtIqtlkVNO+W50knWq0iBPcdvgmjikDG6BZdC4XObaegFKQ4+dy5BDKUGv+apyq+uxEDYnqNUrU2mCpagEgGFQqkhUwIH8/F8bCnCLKUyHG68MU+xQqjkH/icIUqFQIhkyVsx/JevIRYcLcYwNWxRNOzL5cCyng8toBbHR/lXVPo1HPOKA84WyuAVaYr1BODT7te
  template:
    metadata:
      creationTimestamp: null
      name: rucio-db
      namespace: rucio

