apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-server-cvre-rucio-db
  namespace: rucio
spec:
  encryptedData:
    dbconnectstring: AgB0fJZVw8XtOfn5NjilRq3Mg07ltTJGx7SnseHv3CtOB1BgNJv0CJK5ume9NdRf95D+UWx7A/gOimSy3m6oGSFmg5xXwWV2RoVYRKxfs+SeRUtqDSZN0C8ovScq4DNsq0fGdShElYbu3ja6bgdbDyLT9kUThbS5E1RW3AQ1yeSH5OoBcFY/oDHOXbIFmkm2uEW5PiUn5sNbBopFQLRH0xDIXEZdrJSnw0iIb5nvNQfRxe+UEQFtWHv4m5tvoXF4I568ClTTNeunDeM2opGf6M7nmH2JZPj3jsG+8W6nhZc90jX4HHUUwtrJQjf5HJmfrMOlHK+gDBfh9nMssUHpuPhhVTUAAvDg1qhAntQWJp3NXJILsr9NrRWpdhpILC3JC3WpD5OSHGShWsn9qEjumt9M8h9O8PbcVdQAB5CjwYCYz8veJbd0pCPSE01GHN/fB4MOSDtRZGmV2xEbyoTHKo3TQwCHCdTP5qaMjrjwIyKIMMCLOytdsiq+o89VbFoWtaJumLVaN8UtrZXzEU+pQmZY/zOvxjuXIq+L9VgV6AgxNwPSbqM84FVSwrKjfHUpdZg13zxq1TIevcHfZ8+6fIH1QM6V/KTmBEM2/tdxeVvkh8szL9u4gKotZZ+Uo1clVlBHykWIIhtKfWlGHxxl5+BukuvqxIkCX9Tj21RbS6kbdWv51vkzj5LJQmu2SzBVW4gJ/lbDToEQ7R0hWQGgIU8MZ2fO7urTaR9AO8dkw+pDItCA4lzpd5aI7y05qZ7LmkwwXkWA/JT75nIR1YHFKDGc
  template:
    metadata:
      creationTimestamp: null
      name: rucio-server-cvre-rucio-db
      namespace: rucio

