apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servers-vre
  namespace: rucio-vre
spec:
  sources:
  - repoURL: 'https://rucio.github.io/helm-charts/'
    chart: rucio-server
    targetRevision: 1.30.0
    helm:
      valueFiles:
      - $values/infrastructure/cluster/argocd/rucio-vre/rucio-server-values.yaml
  - repoURL: 'https://github.com/vre-hub/vre.git'
    targetRevision: dev
    ref: values
    
# spec:
#   project: default
#   source:
#     chart: server-vre
#     repoURL: https://rucio.github.io/helm-charts/
#     targetRevision: 1.30.0
#     helm:
#       releaseName: servers-vre
#       valueFiles:
#       - rucio-server-values.yaml
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: default
    

 
    
