# to apply to cluster when in need of SSHing into a specific node 
# change the nodeName as you like, according to the Openstack characteristics 

apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 1
  name: ssh-node2
  namespace: elena
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: d
      app.kubernetes.io/name: host-debug
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: d
        app.kubernetes.io/name: host-debug
    spec:
      containers:
      - command:
        - sleep
        - inf
        image: registry.cern.ch/kubernetes/ops:0.3.0
        imagePullPolicy: IfNotPresent
        name: host-debug
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hostfs
          mountPropagation: Bidirectional
          name: hostfs
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeName: cern-vre-bl53fcf4f77h-node-2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 0
        seLinuxOptions:
          type: spc_t
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: PreferNoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /
          type: ""
        name: hostfs
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
