apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rucio-server-cvre-rse-accounts
  namespace: rucio
spec:
  encryptedData:
    rse-s3_config.json: AgCCEXOD03Asoyz9MPd2MvNqW9a3xI2QApkKIgoTbmh4aJ3UC1vb4qJ2VdOFSTPM4D9CSderbUR+jExQLdWxq2jREhZtzPYQDfWjnCy/BVp4H52G00h8oOcxszc6UwKPOEx9Qljsp2lORper39JN+FFhccfBGGHCV7ATh830DMHtTss2VK1/wIiqBY7PJNwoO3TqsnsdQxFNzeuDZaUCzm8Kck7XD1ZPWP0KKKP3whVZKW/NppsgCzCIVoBrQCK/BjG9mbhoo6WpanEo7PL1CAe0tY8IW4lI0mdJh5lhSKQNt8BhRwNa2gjJutw3GvRcwUEKfeCHKk5aqysx1Ivqi1M+nT5pT0XdWDb7VNx6YFIP1KdgvE5tbMHlEl45cGhNaLlBFmjbV386b70gkbyDfQVC+JP4Zrh7YqhhzcRH5Hso4BfdwNZFqG+mnSZYYRukCbUTRNRJRygOgukeYa9EM/UWgjzlly+6KCv4iFXuBgXA4+EXXMLUFT92hCdMt+IBy+OngXCbGkdOFs6x06FCTC8wcqO/HtMUZ7wUPVJa/BWz08mkWkcx/ZwJQSK2oiVX/9QCmfvBjw0A1gXIExuf6IqLvnOkj/yUB6JEzUcmyOPt945UloSbMNAs/FgfgQs87A5G19wBZCyQWzB4JadeuDTPYUSUAmlgk34Ummtcle1VFsDNZDInVqBu01inPFhGdSD8n2dc6l/787eWyVAUH4NKYSMhMOtT4jweR8ClVFGuz8EGAp17o/2nqxlrcNss3VdGliiQY6ceI7AsbBTS2HtNInDyd8f3FWHWSJ9pJY3ggiwtdv03roCREJQf0DiKPD+ZnS6WOa0Dx4yjZ88wr5/z2gVHrQ2TGOG9D7zZUJzd7eVAYrRw2/3zq4+UVXvTGfeiwlu1babJFxWPXMy8LLKouwLEW6fl2XmnrXQW7CXOmtVWsFG5k/vIVi2BFkU5aWs8tU9YJwuElKpM690Yl54mvAveRcjh3xn3DRfDBhEeTokLAgVk/vr3LUyHFh+QnSyOHbz9hZONI/7Ewl0wH1jpoYqcoA==
  template:
    metadata:
      creationTimestamp: null
      name: rucio-server-cvre-rse-accounts
      namespace: rucio

