# apiVersion: source.toolkit.fluxcd.io/v2beta1
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dask-charts
  namespace: dask
spec:
  interval: 5m
  url: https://dask.github.io/helm-chart/
  # url: https://helm.dask.org/
