# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

hub:
  db:
    type: sqlite-memory # change to postgres ref.: https://z2jh.jupyter.org/en/stable/resources/reference.html?highlight=database#hub-db-type
  config:
    KubeSpawner:
      pod_security_context:
        fsGroupChangePolicy: "OnRootMismatch"
  extraConfig:
    00-first-config: |
      c.KubeSpawner.pod_security_context.update({'fsGroupChangePolicy': 'OnRootMismatch'})
  # podSecurityContext:
  #   fsGroup: 0
  # containerSecurityContext:
  #   runAsUser: 0
  #   runAsGroup: 0

proxy:
  service:
    type: LoadBalancer
    loadBalancerIP: 137.138.226.35 # may change if LB needs to be created manually due to bug ref.: openstack loadbalancer create --name kube_service_8d85602e-7816-4153-b85b-ea86586e47c1_jhub_proxy-public --vip-network-id 798d00f3-2af9-48a0-a7c3-a26d909a2d64
    annotations:
      loadbalancer.openstack.org/network-id: "798d00f3-2af9-48a0-a7c3-a26d909a2d64"
      service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
      loadbalancer.openstack.org/cascade-delete: "false"

singleuser:
  # extraPodConfig:
  #   securityContext:
  #     fsGroupChangePolicy: "OnRootMismatch" # value is not set, which causes containers to crash
  # extraEnv:
  #   GRANT_SUDO: "yes"
  #   NOTEBOOK_ARGS: "--allow-root"
  # uid: 0
  # fsGid: 0
  # allowPrivilegeEscalation: true
  # cmd: "start-singleuser.sh"
  storage:
    dynamic:
      storageClass: manila-meyrin-cephfs
