# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

hub:
  db:
    type: postgres
    upgrade: true
  # config:
  #   Authenticator:
  #     auto_login: true
  #     enable_auth_state: true
  #   GenericOAuthenticator:
  #     client_id: your-client-id
  #     client_secret: your-client-secret
  #     oauth_callback_url: https://your-jupyterhub-domain/hub/oauth_callback
  #     authorize_url: https://your-domain.us.auth0.com/authorize
  #     token_url: https://your-domain.us.auth0.com/oauth/token
  #     userdata_url: https://your-domain.us.auth0.com/userinfo
  #     scope:
  #       - openid
  #       - name
  #       - profile
  #       - email
  #     username_key: name
  #   JupyterHub:
  #     authenticator_class: generic-oauth

proxy:
  service:
    type: LoadBalancer
    loadBalancerIP: 137.138.226.36 # may change if LB needs to be created manually due to bug: openstack loadbalancer create --name <lb-name> --vip-network-id <network-id>
    annotations:
      loadbalancer.openstack.org/network-id: "798d00f3-2af9-48a0-a7c3-a26d909a2d64"
      service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
      loadbalancer.openstack.org/cascade-delete: "false"
  https:
    enabled: true
    hosts:
      - nb-vre.cern.ch
    type: secret
    secret:
      name: example-tls # change name later

    # hosts:
    #   - vre-hub.cern.ch
    # letsencrypt:
    #   contactEmail: eosc.future@cern.ch

singleuser:
  storage:
    type: none

# ingress:
#   enabled: true # can be an alternative for LBaaS in combination with proxy.service.type: ClusterIP
#   ingressClassName: nginx
